name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  lottie: ^3.1.2
  http: ^1.6.0
  image_picker: ^1.2.1
  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  image: ^4.8.0
  barcode_widget: ^2.0.4
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  socket_io_client: ^3.1.4
  cached_network_image: ^3.4.1
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  csv: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_dotenv: ^6.0.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_white.png"
  adaptive_icon_background: "#001F5B"
  adaptive_icon_foreground: "assets/images/logo_white_foreground.png"
  remove_alpha_ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/
